<a href="https://colab.research.google.com/github/hiteshpujari/Python/blob/master/Numpy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [0]:
import numpy as np

In [0]:
#Creating sample array
arr = np.arange(10,20)

In [13]:
#Show
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [14]:
#Get a value at an index
arr[8]

18

In [16]:
#Get values in a range
arr[0:5]

array([10, 11, 12, 13, 14])

In [0]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [18]:
#Setting a value with index range (Broadcasting)
arr[0:5]=10

#Show
arr

array([10, 10, 10, 10, 10, 15, 16, 17, 18, 19])

In [19]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,10)

#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [0]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
#Indexing row
arr_2d[4]


In [0]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [0]:
# Getting individual element value
arr_2d[1,0]

20

In [28]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [27]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr>4

In [0]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
